
2024-11-02 16:32:53,425 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 16:32:54,154 - INFO - Conectividade com a internet verificada.
2024-11-02 16:32:54,263 - INFO - IP trocado com sucesso!
2024-11-02 16:32:59,688 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:33:10,219 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:33:28,431 - INFO - Navegador fechado com sucesso.
2024-11-02 16:33:32,790 - INFO - Dados de navegação e cookies limpos com sucesso.
2024-11-02 16:33:32,890 - INFO - IP trocado com sucesso!
2024-11-02 16:33:38,313 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:33:48,835 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:34:45,891 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 16:34:46,570 - INFO - Conectividade com a internet verificada.
2024-11-02 16:34:46,675 - INFO - IP trocado com sucesso!
2024-11-02 16:34:52,103 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:35:02,628 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:35:20,838 - INFO - Navegador fechado com sucesso.
2024-11-02 16:35:25,242 - INFO - Dados de navegação e cookies limpos com sucesso.
2024-11-02 16:35:25,333 - INFO - IP trocado com sucesso!
2024-11-02 16:35:30,778 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:35:41,301 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:40:40,183 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 16:40:40,821 - INFO - Conectividade com a internet verificada.
2024-11-02 16:40:40,920 - INFO - IP trocado com sucesso!
2024-11-02 16:40:46,365 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:41:01,902 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:41:12,136 - INFO - Navegador fechado com sucesso.
2024-11-02 16:41:16,546 - INFO - Dados de navegação e cookies limpos com sucesso.
2024-11-02 16:41:16,648 - INFO - IP trocado com sucesso!
2024-11-02 16:41:22,071 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:41:37,610 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:41:47,852 - INFO - Navegador fechado com sucesso.
2024-11-02 16:49:57,863 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 16:49:58,492 - INFO - Conectividade com a internet verificada.
2024-11-02 16:50:05,612 - ERROR - Falha ao trocar o IP usando proxy.
2024-11-02 16:50:05,612 - ERROR - Não foi possível trocar o IP.
2024-11-02 16:50:08,908 - ERROR - Erro ao trocar IP: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000199B4E91580>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')))
2024-11-02 16:50:08,908 - ERROR - Não foi possível trocar o IP.
2024-11-02 16:50:29,982 - ERROR - Erro ao trocar IP: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000199B551CB00>, 'Connection to 177.93.60.70 timed out. (connect timeout=None)')))
2024-11-02 16:50:29,982 - ERROR - Não foi possível trocar o IP.
2024-11-02 16:50:51,027 - ERROR - Erro ao trocar IP: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000199B551D1C0>, 'Connection to 147.139.208.214 timed out. (connect timeout=None)')))
2024-11-02 16:50:51,027 - ERROR - Não foi possível trocar o IP.
2024-11-02 16:51:12,074 - ERROR - Erro ao trocar IP: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000199B551D850>, 'Connection to 103.155.246.180 timed out. (connect timeout=None)')))
2024-11-02 16:51:12,074 - ERROR - Não foi possível trocar o IP.
2024-11-02 16:51:33,116 - ERROR - Erro ao trocar IP: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000199B551E1E0>, 'Connection to 34.100.189.30 timed out. (connect timeout=None)')))
2024-11-02 16:51:33,116 - ERROR - Não foi possível trocar o IP.
2024-11-02 16:51:36,237 - INFO - IP trocado com sucesso! Usando proxy: http://200.49.242.18:8080
2024-11-02 16:51:41,662 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:51:57,204 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:52:39,688 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 16:52:40,310 - INFO - Conectividade com a internet verificada.
2024-11-02 16:52:44,275 - INFO - IP trocado com sucesso! Usando proxy: http://101.109.50.148:8080
2024-11-02 16:52:49,704 - INFO - Navegador Chrome aberto com sucesso!
2024-11-02 16:53:05,241 - INFO - Vídeo encontrado e iniciado: https://www.youtube.com/shorts/yRMN-ymQReE
2024-11-02 16:53:15,475 - INFO - Navegador fechado com sucesso.
2024-11-02 16:53:19,856 - INFO - Dados de navegação e cookies limpos com sucesso.
2024-11-02 16:53:48,348 - ERROR - Erro ao trocar IP: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))
2024-11-02 16:53:48,348 - ERROR - Não foi possível trocar o IP.
2024-11-02 16:54:09,423 - ERROR - Erro ao trocar IP: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001606681C230>, 'Connection to 147.139.208.214 timed out. (connect timeout=None)')))
2024-11-02 16:54:09,423 - ERROR - Não foi possível trocar o IP.
2024-11-02 17:04:51,286 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 17:06:45,692 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 17:06:47,893 - ERROR - Erro ao verificar a conectividade com a internet: SOCKSHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000022EFB967230>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2024-11-02 17:06:47,893 - INFO - Não foi possível verificar a conectividade com a internet.
2024-11-02 17:08:29,999 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-02 17:08:32,165 - ERROR - Erro ao verificar a conectividade com a internet: SOCKSHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001830B231DC0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2024-11-02 17:08:32,166 - INFO - Não foi possível verificar a conectividade com a internet.
2024-11-09 18:02:51,943 - ERROR - Erro ao solicitar a duração do vídeo: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-11-09 18:02:51,958 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:02:56,079 - ERROR - Erro ao verificar a conectividade com a internet: SOCKSHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001C600135FA0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2024-11-09 18:02:56,079 - INFO - Não foi possível verificar a conectividade com a internet.
2024-11-09 18:03:38,233 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:03:42,399 - ERROR - Erro ao verificar a conectividade com a internet: SOCKSHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000020E740E9F10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2024-11-09 18:03:42,399 - INFO - Não foi possível verificar a conectividade com a internet.
2024-11-09 18:03:58,088 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:04:02,231 - ERROR - Erro ao verificar a conectividade com a internet: SOCKSHTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000201030E9F10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2024-11-09 18:04:02,231 - INFO - Não foi possível verificar a conectividade com a internet.
2024-11-09 18:07:59,538 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:08:07,013 - INFO - Navegador Chrome aberto com sucesso!
2024-11-09 18:09:16,552 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:09:24,001 - INFO - Navegador Chrome aberto com sucesso!
2024-11-09 18:12:06,433 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:12:13,580 - INFO - Navegador Chrome aberto com sucesso!
2024-11-09 18:12:29,117 - INFO - Vídeo encontrado e iniciado: https://www.xvideos.com/video.ummkmbaca66/cannoball_-_os_criadores
2024-11-09 18:26:07,787 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:26:12,796 - INFO - Navegador Chrome aberto com sucesso!
2024-11-09 18:26:28,232 - INFO - Vídeo encontrado e iniciado: https://www.xvideos.com/video.ummkmbaca66/cannoball_-_os_criadores
2024-11-09 18:27:03,437 - INFO - Navegador fechado com sucesso.
2024-11-09 18:27:08,441 - INFO - Navegador Chrome aberto com sucesso!
2024-11-09 18:28:38,499 - INFO - O código de automação para assistir vídeos no YouTube vai começar...
2024-11-09 18:28:43,506 - INFO - Navegador Chrome aberto com sucesso!
2024-11-09 18:28:58,952 - INFO - Vídeo encontrado e iniciado: https://www.xvideos.com/video.ummkmbaca66/cannoball_-_os_criadores
2025-10-18 20:26:06,408 - INFO - Iniciando automação de visualização de vídeos...
2025-10-18 20:26:11,446 - INFO - Navegador Chrome aberto com sucesso.
2025-10-18 20:26:11,446 - INFO - Iniciando vídeo 1/5: https://www.youtube.com/watch?v=dQw4w9WgXcQ
2025-10-18 20:26:16,803 - INFO - Acessando: https://www.youtube.com/watch?v=dQw4w9WgXcQ
2025-10-18 20:26:26,804 - ERROR - Erro ao realizar a pesquisa: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 20:26:36,920 - INFO - Navegador minimizado.
2025-10-18 20:26:39,921 - INFO - Iniciando vídeo 2/5: https://www.youtube.com/watch?v=dQw4w9WgXcQ
2025-10-18 20:26:45,238 - INFO - Acessando: https://www.youtube.com/watch?v=dQw4w9WgXcQ
2025-10-18 20:26:55,244 - ERROR - Erro ao realizar a pesquisa: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 20:29:44,657 - INFO - Iniciando automação de visualização de vídeos...
2025-10-18 20:29:49,684 - INFO - Navegador Chrome aberto com sucesso.
2025-10-18 20:29:49,684 - INFO - Iniciando vídeo 1/5: https://www.youtube.com/watch?v=fxvkI9MTQw4
2025-10-18 20:29:55,012 - INFO - Acessando: https://www.youtube.com/watch?v=fxvkI9MTQw4
2025-10-18 20:30:05,013 - ERROR - Erro ao realizar a pesquisa: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 20:30:33,706 - INFO - Iniciando automação de visualização de vídeos...
2025-10-18 20:30:38,735 - INFO - Navegador Chrome aberto com sucesso.
2025-10-18 20:30:38,735 - INFO - Iniciando vídeo 1/5: https://www.youtube.com/watch?v=fxvkI9MTQw4
2025-10-18 20:30:44,065 - INFO - Acessando: https://www.youtube.com/watch?v=fxvkI9MTQw4
2025-10-18 20:47:49,549 - INFO - Iniciando automação de visualização de vídeos...
2025-10-18 20:47:54,577 - INFO - Navegador Chrome aberto com sucesso.
2025-10-18 20:47:54,577 - INFO - Iniciando vídeo 1/5: https://www.youtube.com/watch?v=H6SZuAcqeW8&list=RDH6SZuAcqeW8&start_radio=1
2025-10-18 20:47:59,922 - INFO - Acessando: https://www.youtube.com/watch?v=H6SZuAcqeW8&list=RDH6SZuAcqeW8&start_radio=1
2025-10-18 20:48:09,923 - ERROR - Erro ao realizar a pesquisa: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 20:56:28,526 - INFO - Iniciando automação...
2025-10-18 20:56:33,555 - INFO - Chrome aberto com sucesso.
2025-10-18 20:56:33,555 - INFO - 🎬 Iniciando vídeo 1/3
2025-10-18 20:56:37,794 - INFO - Acessando: https://www.youtube.com/watch?v=H6SZuAcqeW8
2025-10-18 20:56:45,795 - ERROR - Erro ao realizar pesquisa
Traceback (most recent call last):
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 90, in realizar_pesquisa
    play = esperar_imagem('play_button.png', timeout=12, confidence=0.7)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 71, in esperar_imagem
    pos = pyautogui.locateCenterOnScreen(img_path, confidence=confidence)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programas\PesquisaVideo\.venv\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 20:56:45,799 - INFO - Aguardando 294s...
2025-10-18 20:58:39,782 - INFO - Iniciando automação...
2025-10-18 20:58:44,809 - INFO - Chrome aberto com sucesso.
2025-10-18 20:58:44,810 - INFO - 🎬 Iniciando vídeo 1/3
2025-10-18 20:58:49,306 - INFO - Acessando: https://www.youtube.com/watch?v=H6SZuAcqeW8
2025-10-18 20:58:57,307 - ERROR - Erro ao realizar pesquisa
Traceback (most recent call last):
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 91, in realizar_pesquisa
    play = esperar_imagem('play_button.png', timeout=12, confidence=0.7)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 72, in esperar_imagem
    pos = pyautogui.locateCenterOnScreen(img_path, confidence=confidence)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programas\PesquisaVideo\.venv\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 20:58:57,309 - INFO - Aguardando 303s...
2025-10-18 21:04:00,413 - INFO - Navegador minimizado.
2025-10-18 21:04:05,331 - INFO - 🎬 Iniciando vídeo 2/3
2025-10-18 21:04:09,689 - INFO - Acessando: https://www.youtube.com/watch?v=H6SZuAcqeW8
2025-10-18 21:04:17,689 - ERROR - Erro ao realizar pesquisa
Traceback (most recent call last):
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 91, in realizar_pesquisa
    play = esperar_imagem('play_button.png', timeout=12, confidence=0.7)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 72, in esperar_imagem
    pos = pyautogui.locateCenterOnScreen(img_path, confidence=confidence)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programas\PesquisaVideo\.venv\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 21:04:17,690 - INFO - Aguardando 300s...
2025-10-18 21:07:07,694 - INFO - Iniciando automação de vídeos...
2025-10-18 21:07:15,722 - INFO - Chrome aberto com sucesso.
2025-10-18 21:07:15,722 - INFO - 🎬 Iniciando vídeo 1/3
2025-10-18 21:07:21,345 - INFO - Acessando: https://www.youtube.com/watch?v=H6SZuAcqeW8
2025-10-18 21:07:31,347 - ERROR - Erro ao realizar pesquisa
Traceback (most recent call last):
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 89, in realizar_pesquisa
    if detectar_erro():
       ^^^^^^^^^^^^^^^
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 70, in detectar_erro
    erro = pyautogui.locateOnScreen('erro_macaco.png', confidence=0.8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programas\PesquisaVideo\.venv\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 21:07:31,349 - ERROR - Falha ao carregar o vídeo, pulando.
2025-10-18 21:07:31,451 - INFO - Navegador minimizado.
2025-10-18 21:07:36,946 - INFO - 🎬 Iniciando vídeo 2/3
2025-10-18 21:07:42,562 - INFO - Acessando: https://www.youtube.com/watch?v=H6SZuAcqeW8
2025-10-18 21:07:52,564 - ERROR - Erro ao realizar pesquisa
Traceback (most recent call last):
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 89, in realizar_pesquisa
    if detectar_erro():
       ^^^^^^^^^^^^^^^
  File "d:\Programas\PesquisaVideo\PesquisaVideo.py", line 70, in detectar_erro
    erro = pyautogui.locateOnScreen('erro_macaco.png', confidence=0.8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programas\PesquisaVideo\.venv\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
2025-10-18 21:07:52,565 - ERROR - Falha ao carregar o vídeo, pulando.
2025-10-18 21:07:52,666 - INFO - Navegador minimizado.
2025-10-18 21:07:56,053 - INFO - 🎬 Iniciando vídeo 3/3
2025-10-18 21:08:01,663 - INFO - Acessando: https://www.youtube.com/watch?v=H6SZuAcqeW8
